### PR TITLE
Fix export.module

### PR DESCRIPTION
**Pull request by Mxnuuel**
Nothing too big lol

### CODE REVIEW

**Comment by tgpethan** [comment]
hahaha, I have no idea how I missed that. Thanks dude!

**Comment by tgpethan** [comment]
interestingly the code from before also works fine so I have no idea what V8 is doing there. one of those weird things.

**Comment by Mxnuuel** [comment]
Oh well that happens but i'm glad i spotted it haha

**Comment by Mxnuuel** [comment]
also i'm actually very amazed to see this whole bancho code written in javascript. It's very fascinating for me since i thought about trying it to and then just not do it because i wasn't actually thinking that i could do it.

**Comment by tgpethan** [comment]
hey, took me like 4 years to get to feature completeness since like 2 of those years was figuring out how to actually do stuff. and one of them was 2018 not knowing where to start and slacking for a whole year.
Oh also hope I'm not causing any problems with this, I was pretty concerned about absolutely slamming the server and made this as a result but I'm still not sure if it's enough and this also has it's own set of problems (no queue limiting the number of requests that can be sent to kitsu per fixed interval, etc..)

**Comment by Mxnuuel** [comment]
As far as i can recall is that Kitsu has it's own limiters for requests and even if needed a blacklist if we get slammed to hard. So don't worry if there is anything i'll give you notice 👍

**Pull request merged**
